### ISSUE TITLE
Issue with pattern-behavioural-observer

### ISSUE THREAD

**Issue by johnnyjacq16** [geekific-official/geekific-youtube#3]
@geekific-official 
In your project pattern-behavioural-observer there is an issue.

In the mainApp.java file on line 50, when remove/unsubscribe a listener it was not actually removed from the customer map in notification service since in mainApp.java you used an anonymous object (new EmailMsgListener).
Hence on line 51 it prints 2 subscribers instead of 1.

**Comment by geekific-official** [comment]
I just ran the code and the first call to `store.salePromotion();` (line 46) prints 2 subscribers, and the second one at line 51 prints only 1. Can you explain the issue further please?

**Comment by johnnyjacq16** [comment]
@geekific-official the issue is on my end I am using an old version of Java which does not have the record keyword.
